<div class='page-header'>
  <div class='btn-toolbar pull-right'>
    <div class='btn-group'>
    </div>
  </div>
  <h1>Termine <small>Archiv</small> </h1>
</div>

<div class="table-responsive">
	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th colspan="3">
					<input class="search form-control" placeholder="Suche..." />
				</th>
			</tr>
			<tr>
			<th><a href="#" class="sort" data-sort="name">Titel</a></th>
			<th><a href="#" class="sort" data-sort="location">Ort</a></th>
			<th class="text-right"><a href="#" class="sort" data-sort="date">Datum</a></th>
			<tr>
		</thead>
		<tbody class="list">
			<?php  foreach($this->events as $event): ?>
			<tr>
			<td><a class="name" href="<?= getBase() ?>events/<?= $event->id ?>"><?= $event->name ?></a></td>
			<td class="location"><?= $event->location ?></td>
			<td class="date text-right"><?= date( "d.m.Y", $event->date) ?></td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>	

