<div class='page-header'>
  <div class='btn-toolbar pull-right'>
    <div class='btn-group'>
    </div>
  </div>
  <h1>Termine <small>Archiv</small> </h1>
</div>

<div id="eventlist">
	<table class="table table-striped table-hover table-condensed" cellspacing="0" width="100%">
		<thead>
			<tr>
				<th colspan="3">
					<input class="search form-control" placeholder="Suche..." />
				</th>
			</tr>
			<tr>
			<th width="30%"><button class="sort btn form-control btn-sm btn-default asc" data-sort="name">Titel</button></th>
			<th><button class="sort btn form-control btn-sm btn-default" data-sort="location">Ort</button></th>
			<th width="25%"><button class="sort btn form-control btn-sm btn-default" data-sort="date">Datum</button></th>
			<tr>
		</thead>
		<tbody class="list">
			<?php  foreach($this->events as $event): ?>
			<tr>
			<td><a class="name" href="<?= getBase() ?>events/<?= $event->id ?>"><?= $event->name ?></a></td>
			<td class="location"><?= $event->location ?></td>
			<td class="date"><?= $event->date ?></td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>	

