<div class='page-header'>
  <h1>Termine <small>Übersicht</small> </h1>
  <div class=''>
    <div class=''>
      <a href="<?= getBase() ?>events/new" class="btn btn-primary" > Neuer Termin</a>
      <span>&nbsp;</span>
      <a href="<?= getBase() ?>archive" class="btn btn-danger">Archivierte Termine</a>
    </div>
  </div>
</div>

<div class="panel-group" id="accordion">

  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse1"><i class="fa fa-fw fa-calendar"></i> Kalenderansicht</a>
      </h4>
    </div>
    <div id="collapse1" class="panel-collapse collapse">
      <div id="eventcalendar"></div>
    </div>
  </div>


  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#eventlist"><i class="fa fa-fw fa-list"></i> Listenansicht</a>
      </h4>
    </div>
    <div id="eventlist" class="panel-collapse collapse table-responsive in">
      <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th colspan="5">
          <input class="search form-control" placeholder="Suche..." />
        </th>
      </tr>
      <tr>
        <th class="text-center"><a href="#" class="sort" data-sort="date">Datum</a></th>
        <th class="text-left"><a href="#" class="sort" data-sort="name">Titel</a></th>
        <th class="text-left"><a href="#" class="sort" data-sort="location">Ort</a></th>
        <th class="text-center"><a href="#" class="sort" data-sort="status">Status</a></th>
        <th class="text-center hidden-xs"><a href="#" class="sort" data-sort="count">Zusagen</a></th>
      <tr>
    </thead>
    <tbody class="list">
      <?php foreach($this->events as $event): ?>
      <tr class="eventdata" data-id="<?= $event['id'] ?>" data-title="<?= $event['name'] ?>" data-location="<?= $event['location'] ?>" data-start="<?= $event['date'] * 1000 ?>" data-end="<?= $event['end'] * 1000 ?>">
        <td class="text-center"><span class="date text-hide"><?= $event['date'] ?></span><?= date( "d.m.Y", $event['date']) ?></td>
        <td><a class="name" href="<?= getBase() ?>events/<?= $event['id'] ?>"><?= $event['name'] ?></a></td>
        <td class="location"><?= $event['location'] ?></td>
        <td class="text-center"><span class="status label label-<?= status2class($event['status']) ?>"><?= status2text($event['status']) ?></span></td>
        <td class="text-center"><span class="count"><?= $event['boys'] + $event['girls'] ?></span>&nbsp;&nbsp;<small>( <?= $event['boys']?> <i class="fa fa-mars"></i> / <?=$event['girls'] ?> <i class="fa fa-venus"></i> )</small></td>
      </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
    </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#abo"><i class="fa fa-fw fa-rss"></i> Abonnieren</a>
      </h4>
    </div>
    <div id="abo" class="panel-collapse collapse">
      <p>Unter folgendem Link kannst Du die geplanten Termine herunterladen und/oder abonnieren:</p>
      <a class="list-group-item" href="<?= getBase() ?>events/calendar.ics"><?= getBase() ?>events/calendar.ics</a>
      <h5> Anleitungen zum abonnieren von Kalendern</h5>
      <div class="btn-group">
        <a href="https://support.apple.com/de-de/HT202361" class="btn btn-sm btn-primary" target="_blank">Mac OSX</a>
        <a href="https://support.google.com/calendar/answer/37118?hl=de" class="btn btn-sm btn-primary" target="_blank">Google</a>
        <a href="http://www.ff-altenschwand.de/seiten/service/ical/android.html" class="btn btn-sm btn-primary" target="_blank">Android</a>
        <a href="https://support.apple.com/de-de/HT202361" class="btn btn-sm btn-primary" target="_blank">iOS</a>
      </div>
    </div>
  </div>

  </div>
</div>