<div class='page-header'>
  <div class='btn-toolbar pull-right'>
	  
    <div class='btn-group'>
    </div>
  </div>
  <h1>Extern <small>Links</small> </h1>
  <div class=''>
    <div class=''>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newLinkModal"> Neuer Link </button>
    </div>
  </div>
</div>

<div id="linklist" class="table-responsive">
	<table class="table table-striped table-hover table-condensed">
		<thead>
			<tr>
				<th colspan="4">
					<input class="search form-control" placeholder="Suche..." />
				</th>
			</tr>
			<tr>
			<th><a href="#" class="sort text-left" data-sort="name">Titel</a></th>
			<th><a href="#" class="sort text-left" data-sort="link">Link</a></th>
			<th><a href="#" class="sort text-left" data-sort="link">Info</a></th>
			<th><a href="#" class="sort text-right" data-sort="date">Datum</a></th>
			<tr>
		</thead>
		<tbody class="list">
			<?php  foreach($this->links as $link): ?>
			<tr>
			<td class="text-left">
  				<span>&nbsp;<?= $link->name ?></span>
			</td>
			<td class="link text-left"><a target="_blank" class="name" href="<?= $link->link ?>"><?= $link->link ?></a></td>
			<td class="text-left">
  				<span>&nbsp;<?= $link->description ?></span>
			</td>
			<td class="date text-right"><?= date( "d.m.y", $link->date ) ?></td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>	


<div class="modal fade" id="newLinkModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <form action="<?= getBase() ?>extern" method="POST">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Link hinzufügen</h4>
      </div>
      <div class="modal-body">
	      
	      <div class="form-group">
		  	<label>Titel</label>
		  	<input type="text" name="name" class="form-control">
  		  </div>
  		  
  		  <div class="form-group">
		  	<label>Link</label>
		  	<input type="text" name="link" class="form-control">
  		  </div>
  		  
  		  <div class="form-group">
		  	<label>Beschreibung</label>
		  	<textarea type="text" name="description" class="form-control" placeholder="z.B. Turnier Orga, Doodle, etc ..." resize="0" rows="5"></textarea>
  		  </div>
  		</div>
  	<div class="modal-footer">
  		  	<button type="button" class="btn btn-default" data-dismiss="modal">Abbrechen</button>
  		  	<button type="submit" class="btn btn-primary">Speichern</button>
    </div>	
  </div>
  </form>
</div>