<div class='page-header'>
  <div class='btn-toolbar pull-right'>
	  <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#newLinkModal"> Neuer Link </button>
    <div class='btn-group'>
    </div>
  </div>
  <h1>Extern <small>Links</small> </h1>
</div>

<div id="linklist">
	<table class="table table-striped table-hover table-condensed" cellspacing="0" width="100%">
		<thead>
			<tr>
				<th colspan="3">
					<input class="search form-control" placeholder="Suche..." />
				</th>
			</tr>
			<tr>
			<th width="40%"><button class="sort btn form-control btn-sm btn-default asc" data-sort="name">Titel</button></th>
			<th><button class="sort btn form-control btn-sm btn-default" data-sort="link">Link</button></th>
			<th width="15%"><button class="sort btn form-control btn-sm btn-default" data-sort="date">Datum</button></th>
			<tr>
		</thead>
		<tbody class="list">
			<?php  foreach($this->links as $link): ?>
			<tr>
			<td>
				
				<span  class="label label-info" data-container="body" data-toggle="popover" data-placement="right" data-content="<?= $link->description ?>">
					<i class="fa fa-fw fa-info" aria-hidden="true"></i>
  				</span>
  				<span>&nbsp;<?= $link->name ?></span>
			</td>
			<td class="link"><a target="_blank" class="name" href="<?= $link->link ?>"><?= $link->link ?></a></td>
			<td class="date text-center"><?= date( "d.m.y", $link->date ) ?></td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>	


<div class="modal fade" id="newLinkModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <form action="<?= getBase() ?>extern" method="POST">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Link hinzufügen</h4>
      </div>
      <div class="modal-body">
	      
	      <div class="form-group">
		  	<label>Titel</label>
		  	<input type="text" name="name" class="form-control">
  		  </div>
  		  
  		  <div class="form-group">
		  	<label>Link</label>
		  	<input type="text" name="link" class="form-control">
  		  </div>
  		  
  		  <div class="form-group">
		  	<label>Beschreibung</label>
		  	<textarea type="text" name="description" class="form-control" placeholder="z.B. Turnier Orga, Doodle, etc ..." resize="0" rows="5"></textarea>
  		  </div>
  		</div>
  	<div class="modal-footer">
  		  	<button type="button" class="btn btn-default" data-dismiss="modal">Abbrechen</button>
  		  	<button type="submit" class="btn btn-primary">Speichern</button>
    </div>	
  </div>
  </form>
</div>