<div class='page-header'>
  <div class='btn-toolbar pull-right'>
    	
  </div>
  <h1>Gruppen <small>Übersicht</small></h1>
  <div class=''>
    <div class=''>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newGroupModal"> Neue Gruppe </button>
    </div>
  </div>
</div>


<div id="playerlist">
	
	<div class="table-responsive">			
		<table class="table table-striped table-hover table-responsive">
			<thead>
				<tr>
					<th colspan="2"><input class="search form-control" placeholder="Suchen..." /></th>
				</tr>
				<tr>
					<th class="text-left">
						<a href="#" class="sort" data-sort="name">Name</a>
					</th>
					<th>
						<a href="#" class="sort" data-sort="members">Mitglieder</a>
					</th>

				</tr>
			</thead>
			<tbody class="list">
				<?php  foreach($this->groups as $group): ?>
				<tr>
					<td class="name text-left">
						<a class="name" href="<?= getBase() ?>group/<?= $group['id'] ?>"><?= $group['title'] ?></a>
					</td>
					<td>
						<?= $group['members'] ?>
					</td>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>

<div class="modal fade" id="newGroupModal">
  <form action="<?= getBase() ?>group" method="POST">
  <input type="hidden" name="action" value="newgroup">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Neue Gruppe</h4>
      </div>
      <div class="modal-body">
	      
	      <div class="form-group">
		  	<label>Gruppenname</label>
		  	<input type="text" name="name" class="form-control">
  		  </div>

  		  <div class="form-group">
  		  	<label>Mitglieder</label>
  		  	<select id="messagereceiver" multiple="multiple">
				<?php foreach($this->players as $player): ?>
					<option value="<?= $player['id'] ?>"><?= $player['name'] ?></option>
				<?php endforeach; ?>
				</select>
  		  </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Abbrechen</button>
        <button type="submit" class="btn btn-primary">Speichern</button>
      </div>
    </div>
  </div>
  </form>
</div>
