<div class='page-header'>
  <div class='btn-toolbar pull-right'>
    <div class='btn-group'>
    </div>
  </div>
  <h1>Nachrichten <small>Verfassen</small> </h1>
</div>

<p>
	Alle Nachrichten an <?= getConfig('mail')->address ?> werden von allen Spieler*Innen empfangen, die die Mailingliste in ihrem Profil aboniert haben. Hier kann man Nachrichten an bestimmte Empfänger*Innen schicken.
</p>

<div class="container-fluid">
	<form method="POST" id="messageform">
		<div class="panel panel-default">
			<div class="panel-heading"> Absender </div>
			<div class="panel-body">
				<select id="messagesender" required="" name="senderid">
				<option value="">Absender wählen</option>
				<?php foreach($this->players as $player): ?>
					<option value="<?= $player['id'] ?>"<?= $player['mail'] ? "" : " disabled"?>><?= $player['name'] ?></option>
				<?php endforeach; ?>
				</select>
			</div>
		</div>
		<div class="panel panel-default">
			<div class="panel-heading"> Empfänger*Innen </div>
			<div class="panel-body">
				<select id="messagereceiver" multiple="multiple">
				<?php foreach($this->players as $player): ?>
					<option value="<?= $player['id'] ?>"<?= $player['mail'] ? "" : " disabled"?>><?= $player['name'] ?></option>
				<?php endforeach; ?>
				</select>
			</div>
		</div>
		<div class="panel panel-default">
		<div class="panel-heading"> Nachricht </div>
		<div class="panel-body">
			<div class="row">
				<div class="col-md-10">
					<input type="text" class="form-control" name="subject" placeholder="Betreff"/>
				</div>
				<div class="col-md-2">
					<button type="submit" class="btn btn-primary form-control">Senden</button>
				</div>
			</div>
			
		</div>
		<textarea name="message" id="summernote" placeholder="Nachricht"></textarea>
		
	</form>
</div>