<div class='page-header'>
  <div class='btn-toolbar pull-right'>
    <div class='btn-group'>
    </div>
  </div>
  <a href="<?= getBase() ?>messages"><i class="fa fa-fw fa-chevron-left"></i> Zurück</a>
  <h1>Nachricht</h1>
</div>



<div class="container-fluid">
	<div class="panel panel-default">
	<div class="panel-heading"> Nachricht von <?= $this->fromName ?> </div>
	<div class="panel-body">
		<?= $this->html ?>
	</div>
</div>
</div>