<div class='page-header'>
  <div class='btn-toolbar pull-right'>
    <div class='btn-group'>
    </div>
  </div>
  <a href="<?= getBase() ?>messages"><i class="fa fa-fw fa-chevron-left"></i> Zurück</a>
  <h1>Nachricht</h1>
</div>

<div class="container-fluid">
	<div class="panel panel-default">
	<div class="panel-heading"> Absender: <?= iconv_mime_decode($this->fromName) ?><span class="pull-right text-right"><?= $this->header->date ?></span> </div>
	<div class="panel-body">
		<?= $this->html ?>
	</div>
</div>
</div>