<div class='page-header'>
  <div class='btn-toolbar pull-right'>
    <div class='btn-group'>
      <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#newPlayerModal"> Neue/r Spieler*In </button>
    </div>
  </div>
  <h1>Spieler*Innen <small>Übersicht</small></h1>
</div>


<div id="playerlist">
				
	<table  width="100%" class="table table-striped table-hover" cellspacing="0" width="100%">
		<thead>
			<tr>
				<th  width="100%" colspan="5"><input class="search form-control" placeholder="Suchen..." /></th>
			</tr>
			<tr>
				<th width="5%" class="text-center"><span class="sort btn btn-default btn-sm form-control" data-sort="number">#</span></th>
				<th width="30%"><span class="sort btn btn-default btn-sm form-control" data-sort="name">Name</span></th>
				<?php if(getConfig('playerlist')->mail): ?>
				<th width="55%" class="text-center"><span class="sort btn btn-default btn-sm form-control" data-sort="mail">Email</span></th>
				<?php endif; ?>
				<th width="5%" class="text-center"><span class="sort btn btn-default btn-sm form-control" data-sort="sex"><i class="fa fa-fw fa-transgender-alt"></i></span></th>
				<?php if(getConfig('playerlist')->balance): ?>
				<th width="5%" class="text-right"><span class="sort btn btn-default btn-sm form-control" data-sort="balance">Guthaben</span></th>
				<?php endif; ?>
			<tr>
		</thead>
		<tbody class="list">
			<?php  foreach($this->players as $player): ?>
			<tr>
			<td class="number text-center"><?= $player['number'] ?></td>
			<td><a class="name" href="<?= getBase() ?>player/<?= $player['id'] ?>"><?= $player['name'] ?></a></td>
			<?php if(getConfig('playerlist')->mail): ?>
			<td class="nowrap"><span class="mail"><?= $player['mail'] ?></span></td>
			<?php endif; ?>
			<td class="sex text-center"><?= $player['sex'] ?></td>
			<?php if(getConfig('playerlist')->balance): ?>
			<td class="text-right">
				<span class="balance text-<?= floatval($player['balance'])<0 ? "danger" : "success" ?>"><?= $player['balance'] != NULL ?  number_format(floatval($player['balance']),2) : 0 ?> €</span>
			</td>
			<?php endif; ?>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>

<div class="modal fade" id="newPlayerModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <form action="<?= getBase() ?>player" method="POST">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Spieler hinzufügen</h4>
      </div>
      <div class="modal-body">
	      
	      <div class="form-group">
		  	<label>Name</label>
		  	<input type="text" name="name" class="form-control">
  		  </div>
  		  
  		  <div class="form-group">
		  	<label>Email</label>
		  	<input type="email" name="mail" class="form-control">
  		  </div>
  		  
  		  <div class="form-group">
		  	<label>Rückennummer</label>
		  	<input type="number" name="number" class="form-control" value="1">
  		  </div>
  
  		  <div class="form-group">
  		  	<label>Geschlecht</label>
  		  	<select class="form-control" name="sex">
	   			<option value="w">Weiblich</option>
	   			<option value="m" selected="">Männlich</option>
			</select>
  		  </div>
  		  
  		  <div class="checkbox">
  		  	<label>
  		  		<input type="checkbox" name="receiveMail"> Abonniere Mailinglist
  		  	</label>
  		  </div>
  		  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Abbrechen</button>
        <button type="submit" class="btn btn-primary">Speichern</button>
      </div>
    </div>
  </div>
  </form>
</div>
