<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
        <meta content="width=device-width, initial-scale=1" name="viewport"/>
        <meta content="" name="description"/>
        <meta content="" name="author"/>
        <title>
            <?= getName() ?>
        </title>
        <?php if(getConfig('dev')): ?>
        <link href="<?= getBase() ?>public/css/bootstrap.min.css" rel="stylesheet"/>
        <link href="<?= getBase() ?>public/css/bootstrap-datetimepicker.min.css" rel="stylesheet"/>
        <link href="<?= getBase() ?>public/css/bootstrap-calendar.css" rel="stylesheet"/>
        <link href="<?= getBase() ?>public/css/sb-admin.css" rel="stylesheet"/>
        <link href="<?= getBase() ?>public/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?= getBase() ?>public/summernote/summernote.css" rel="stylesheet"/>
        <link href="<?= getBase() ?>public/css/bootstrap-multiselect.css" rel="stylesheet"/>
        <link href="<?= getBase() ?>public/css/main.css" rel="stylesheet"/>
        <?php else: ?>
        <link href="<?= getBase() ?>public/css/dist.css" rel="stylesheet"/>
        <?php endif; ?>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    </head>
    <body>
        <div id="wrapper">
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="navbar-header">
                    <button class="navbar-toggle" data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button">
                        <span class="sr-only">
                            Toggle navigation
                        </span>
                        <span class="icon-bar">
                        </span>
                        <span class="icon-bar">
                        </span>
                        <span class="icon-bar">
                        </span>
                    </button>
                    <a class="navbar-brand" href="<?= getBase() ?>">
                        <?= getName() ?>
                    </a>
                </div>
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav side-nav">
                        <li>
                            <a href="<?= getBase() ?>events">
                                <i class="fa fa-fw fa-calendar">
                                </i>
                                Termine
                            </a>
                        </li>
                        <li>
                            <a href="<?= getBase() ?>player">
                                <i class="fa fa-fw fa-user">
                                </i>
                                Spieler*Innen
                            </a>
                        </li>
                        <li>
                            <a href="<?= getBase() ?>groups">
                                <i class="fa fa-fw fa-group">
                                </i>
                                Gruppen
                            </a>
                        </li>
<!--                         <li>
                            <a href="<?= getBase() ?>archive">
                                <i class="fa fa-fw fa-archive">
                                </i>
                                Archiv
                            </a>
                        </li> -->
                        <li>
                            <a href="<?= getBase() ?>messages">
                                <i class="fa fa-fw fa-envelope">
                                </i>
                                Nachrichten
                            </a>
                        </li>
                        <li>
                            <a href="<?= getBase() ?>extern">
                                <i class="fa fa-fw fa-external-link">
                                </i>
                                Extern
                            </a>
                        </li>
                        <?php if( isPrivate() ): ?>
                        <li>
                            <a href="<?= getBase() ?>logout">
                                <i class="fa fa-fw fa-sign-out">
                                </i>
                                Abmelden
                            </a>
                        </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </nav>
            <div id="page-wrapper">
                <div class="container-fluid">
                    <div id="alertbox">
                        <?php 
                  foreach($this->
                        flashes() as $type=>$flash):
                    foreach($flash as $flash=>$msg):
                ?>
                        <div class="alert alert-<?= $type ?> alert-dismissible" role="alert">
                            <button aria-label="Close" class="close" data-dismiss="alert" type="button">
                                <span aria-hidden="true">
                                    ×
                                </span>
                            </button>
                            <p>
                                <?= $msg ?>
                            </p>
                        </div>
                        <?php 
                     endforeach;
                  endforeach;  
                ?>
                    </div>
                    <?= $this->yieldView(); ?>
                </div>
            </div>
        </div>
        <script>
            var jsbase = '<?= getBase() ?>';
        </script>
        <?php if(getConfig('dev')): ?>
        <script src="<?= getBase() ?>public/js/jquery.js">
        </script>
        <script src="<?= getBase() ?>public/js/bootstrap.min.js">
        </script>
        <script src="<?= getBase() ?>public/js/bootstrap-datetimepicker.min.js">
        </script>
        <script src="<?= getBase() ?>public/js/bootstrap-calendar.js">
        </script>
        <script src="<?= getBase() ?>public/js/bootstrap-typeahead.js">
        </script>
        <script src="<?= getBase() ?>public/js/bootstrap-multiselect.js">
        </script>
        <script src="<?= getBase() ?>public/js/list.js">
        </script>
        <script src="<?= getBase() ?>public/js/sortable.js">
        </script>
        <script src="<?= getBase() ?>public/summernote/summernote.min.js">
        </script>
        <script src="<?= getBase() ?>public/summernote/lang/summernote-de-DE.js">
        </script>
        <script src="<?= getBase() ?>public/js/main.js">
        </script>
        <?php else: ?>
        <script src="<?= getBase() ?>public/js/dist.js">
        </script>
        <?php endif;?>
    </body>
</html>
